drop table if exists todo;
create table todo (
                       id bigint generated by default as identity,
                       content varchar(2000),
                       done boolean,
                       created_at timestamp,
                       updated_at timestamp,
                       primary key (id)
);

insert into todo (content, done, created_at)
VALUES ('todo1', false, now()),
       ('todo2', false, now());